name: Build and publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up QEMU (for cross-platform builds, optional)
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/regex-tower:latest
          file: Dockerfile
          # optionally build multi-arch images:
          # platforms: linux/amd64,linux/arm64


      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.153.0/doctl-1.153.0-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin/

      - name: Authenticate doctl
        run: doctl auth init -t ${{ secrets.DO_API_TOKEN }}

      - name: Update Container App to use new image
        run: |
          APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | grep regex-tower | awk '{print $1}')
          doctl apps create-deployment $APP_ID